#Array with zeros & ones
import numpy as np
zeros_array1 = np.zeros(5) # zeros(shape) -> ((row,colums))
print(zeros_array1)
print()
zeros_array2 = np.zeros((4,4))
print(zeros_array2)
print()
zeros_array3 = np.zeros((2,3))
print(zeros_array3)
print("\n\n")
ones_array1 = np.ones(6) # ones(shape) -> ((row,colums))
print(ones_array1)
print()
ones_array2 = np.ones((4,4))
print(ones_array2)
print()
ones_array3 = np.ones((4,2))
print(ones_array3)